'use client';

import { Download } from 'lucide-react';
import type { TripDetail } from '@/lib/services/trips';

export function DownloadTripPDFButton({ trip }: { trip: TripDetail }) {
  function handleDownload() {
    const lines: string[] = [];
    lines.push('EASEWITHSTAY — ITINERARY');
    lines.push('========================');
    lines.push('');
    lines.push(trip.title);
    if (trip.destination) lines.push(`Destination: ${trip.destination.name}`);
    lines.push(`Days: ${trip.days.length}`);
    if (trip.budgetMinor) {
      const currency = trip.currency === 'INR' ? 'Rs ' : trip.currency + ' ';
      lines.push(
        `Estimated total: ${currency}${(trip.budgetMinor / 100).toLocaleString('en-IN')}`,
      );
    }
    lines.push('');
    lines.push('------------------------');
    lines.push('');

    for (const day of trip.days) {
      lines.push(`DAY ${day.dayIndex + 1} — ${day.title ?? ''}`);
      if (day.notes) lines.push(`(${day.notes})`);
      lines.push('');
      for (const item of day.items) {
        const meta = item.metadata as
          | { startTime?: string | null }
          | null
          | undefined;
        const time = meta?.startTime ?? '';
        const timePrefix = time ? `${time} — ` : '';
        const cost =
          item.costMinor && item.costMinor > 0
            ? ` (Rs ${(item.costMinor / 100).toLocaleString('en-IN')})`
            : '';
        lines.push(`  ${timePrefix}${item.title}${cost}`);
        if (item.notes) lines.push(`      ${item.notes}`);
      }
      lines.push('');
    }

    lines.push('------------------------');
    lines.push('Generated by EaseWithStay');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${trip.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <button
      type="button"
      onClick={handleDownload}
      className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--color-coral)] px-3.5 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--color-coral-dark)]"
    >
      <Download size={14} />
      Download
    </button>
  );
}